/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args) {
        Server server = new Server(6157);
        server.run(2);
    }
}
